name: Test
on: [push, pull_request]

jobs:
  test:
    name: Unit tests on Ubuntu
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        neovim: [true, false]
        version: [stable, nightly]
        # Exclude Neovim nightly since it's unstable
        exclude:
          - neovim: true
            version: nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install ripgrep
        run: cargo install ripgrep
      - name: Checkout vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.neovim }}
      - name: Run unit tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./vim-themis/bin/themis ./test

  test-windows:
    name: Unit tests on Windows
    strategy:
      matrix:
        neovim: [true, false]
        version: [stable, nightly]
        # Exclude Neovim nightly since it's unstable
        exclude:
          - neovim: true
            version: nightly
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.neovim }}
      - name: Run unit tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: ./vim-themis/bin/themis.bat ./test

  vint:
    name: Run vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install vim-vint
      - run: vint --warning --verbose --enable-neovim ./autoload
