name: Test
on: [push, pull_request]

jobs:
  test:
    name: Unit tests on Ubuntu
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        neovim: [true, false]
        version: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install ripgrep
        run: cargo install ripgrep
      - name: Checkout vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.neovim }}
      - name: Run unit tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
          THEMIS_PROFILE: profile.txt
        run: ./vim-themis/bin/themis ./test
      - uses: codecov/codecov-action@v2
        with:
          files: profile.txt
          fail_ci_if_error: true
          verbose: true

  test-windows:
    name: Unit tests on Windows
    timeout-minutes: 10
    strategy:
      matrix:
        neovim: [true, false]
        version: [stable, nightly]
        exclude:
          # No stable Vim release is officially provided for Windows
          - neovim: false
            version: stable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install ripgrep
        run: cargo install ripgrep
      - name: Checkout vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.neovim }}
      - name: Run unit tests
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
          THEMIS_PROFILE: profile.txt
        run: ./vim-themis/bin/themis ./test
      - uses: codecov/codecov-action@v2
        with:
          files: profile.txt
          fail_ci_if_error: true
          verbose: true

  vint:
    name: Run vint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - run: pip install vim-vint
      - run: vint --warning --verbose --enable-neovim ./autoload
